  language: java
  install: cd PlaynomicsSDK && mvn install -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6 -DskipTests=true
  script: mvn test -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6
  build_environment : Ubuntu1304
